### ISSUE TITLE
Feature Request: Add a version selector

### ISSUE THREAD

**Issue by MiniDigger** [DemonWav/BuildToolsGUI#3]
A way to select the minecraft version you want to build would be cool. 
Should be easy for you to implement since you only need to add a --rev 1.8 or --rev 1.9 or whatever as a java argument.
If I would unterstand c# I would create a pr but sadly I don't ^^

**Comment by DemonWav** [comment]
I'll add this. I had to manually change the code for 1.9 which was kinda dumb.

**Comment by MiniDigger** [comment]
well, I needed to power up my vps to get a 1.9 build ^^

**Comment by DemonWav** [comment]
Added this, redownload BuildToolsGUI for feature.
